### PR TITLE
Use After Effects 24.5.0x41 per-character styles

### LINKED ISSUE #1: Example AE project file
Hey! This is a neat library. I'm curious how you use this in your After Effects templates. I see in the description you mention:

> This can then be used in Ae to style and position **a bunch of text layers**.

Seems like this is clever work around for the limitation you mention in [your article](https://motiondeveloper.com/blog/text-style-expressions):

> There's no `setStyleAt()` - it's not possible to set different styles for different portions of the text. The returned style object is used for all characters.

It would be sweet to see how you wire this up!

----

Edit: Ah, looks like we'll get per-character text styling in expressions soon—[currently in beta](https://community.adobe.com/t5/after-effects-beta-discussions/now-in-beta-per-character-text-and-paragraph-styling-in-expressions/m-p/14624910/thread-id/3560)!

----

Update: I had a chance to update this lib for use with the 24.5.0x41 beta, see #2!

### PR DESCRIPTION
**Pull request by fartinmartin**
Inspired by [this post](https://community.adobe.com/t5/after-effects-beta-discussions/now-in-beta-per-character-text-and-paragraph-styling-in-expressions/m-p/14624910/thread-id/3560) (in particular Volition74au's use of `eval()` in the comments), I've updated this lib for use with After Effects 24.5.0x41 per-character styles expressions—AKA markdown in a single `TextLayer`!

It strays a bit from the original, but maybe that makes sense given the new AE features.

An example expression with the new lib looks like:

```js
const { parse } = footage('style-parser.jsx').sourceData.get();

const inputText = `# hello!

this next word will be *bold*
and this one will be _italic_

## but check this one out:

i will be ==highlighted==!!!`

const customParsers = [
  {
    style: 'highlight',
    matcher: /==(.+?)==/g,
    transforms: [
      { method: 'setFillColor', value: [1, 1, 0, 1] },
    ],
  },
];

const render = parse(inputText, customParsers);
render();
```

Here's a project file to play with: [ae-md.zip](https://github.com/user-attachments/files/17070221/ae-md.zip)

### CODE REVIEW

**Comment by fartinmartin** [comment]
Updated the API a bit:

```js
const { parse } = footage("style-parser.jsx").sourceData.get();

const inputText = `# hello!

this next word will be *bold*
and this one will be _italic_

## but check this one out:

i will be ==highlighted==!!!`

const fontMap = {
  regular: "Menlo-Regular",
  bold: "Menlo-Bold",
  italic: "Menlo-Italic",
};

const customParsers = [
  {
    style: "highlight",
    matcher: /==(.+?)==/g,
    // styles map to AE's style methods (e.g. `setFillColor` becomes `fillColor`)
    styles: { fillColor: [1, 1, 0] },
  },
];

const render = parse({
  markdown: inputText,
  // optional props:
  fonts: fontMap,
  parsers: customParsers,
});

render();
```

Updated project file: [ae-md.zip](https://github.com/user-attachments/files/17384463/ae-md.zip)

**Comment by timhaywood** [comment]
Amazing work @fartinmartin, super impressed. This is a way better API/functionality. It would be nice to avoid the `eval()` though, so I might see if there's a cleaner way we can do that part (though maybe it doesn't matter!).

Was there a specific reason you created a local copy of `rollup-plugin-ae-jsx`?

**Comment by fartinmartin** [comment]
Thanks @timhaywood! Agreed—it would be nice to avoid `eval()` if possible!

Haha, yeah, as I started to reference functions in others I needed to export them in a `get` function scope, like you have done in your [aefunctions.jsx](https://github.com/motiondeveloper/aefunctions/blob/a6a777177fe0e0acb5451a0f0f265fecd41153a1/src/index.ts#L18) lib. I've got [a PR](https://github.com/motiondeveloper/rollup-plugin-ae-jsx/pull/1) with this feature for `rollup-plugin-ae-jsx` as well if that's something you'd want to include in the plugin going forward!

**Comment by timhaywood** [comment]
Oh great idea! Wrapping everything in the `get()` function at compile time is a much better authoring experience.

I'll approve that PR first and then we can work on this one. Changed this to target a dev branch so we can work on it alongside main before merging.

**Comment by fartinmartin** [comment]
Nice! I just tested using `reduce` instead of `eval` and it seems to work!

**Pull request merged**
